# Generated by Django 5.1.5 on 2026-01-28 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='containershipment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='core.client'),
        ),
    ]
