# Generated by Django 5.1.5 on 2026-01-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
        ('accounts', '0002_user_avatar'),
    ]

    operations = [
    ]
