# Generated by Django 5.1.5 on 2026-01-28 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_local_avatar'),
        ('accounts', '0004_alter_user_avatar'),
    ]

    operations = [
    ]
