# Generated by Django 5.1.5 on 2026-01-28 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_0003_user_local_avatar_0004_alter_user_avatar'),
        ('core', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('BOSS', 'Boss'), ('HQ_ADMIN', 'HQ Admin'), ('BRANCH_AGENT', 'Branch Agent'), ('ACCOUNTING', 'Accounting'), ('CLIENT', 'Client')], max_length=20),
        ),
    ]
